package io.github.xunuosi.tb.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.github.xunuosi.tb.model.bean.Player;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tb_player".
*/
public class PlayerDao extends AbstractDao<Player, Long> {

    public static final String TABLENAME = "tb_player";

    /**
     * Properties of entity Player.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sex = new Property(1, String.class, "sex", false, "SEX");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Num = new Property(3, int.class, "num", false, "NUM");
        public final static Property TeamId = new Property(4, int.class, "teamId", false, "TEAM_ID");
        public final static Property TeamName = new Property(5, String.class, "teamName", false, "TEAM_NAME");
        public final static Property CardNum = new Property(6, String.class, "cardNum", false, "CARD_NUM");
        public final static Property Position = new Property(7, String.class, "position", false, "POSITION");
    }


    public PlayerDao(DaoConfig config) {
        super(config);
    }
    
    public PlayerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tb_player\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SEX\" TEXT," + // 1: sex
                "\"NAME\" TEXT," + // 2: name
                "\"NUM\" INTEGER NOT NULL ," + // 3: num
                "\"TEAM_ID\" INTEGER NOT NULL ," + // 4: teamId
                "\"TEAM_NAME\" TEXT," + // 5: teamName
                "\"CARD_NUM\" TEXT," + // 6: cardNum
                "\"POSITION\" TEXT);"); // 7: position
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tb_player\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Player entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(2, sex);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getNum());
        stmt.bindLong(5, entity.getTeamId());
 
        String teamName = entity.getTeamName();
        if (teamName != null) {
            stmt.bindString(6, teamName);
        }
 
        String cardNum = entity.getCardNum();
        if (cardNum != null) {
            stmt.bindString(7, cardNum);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(8, position);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Player entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(2, sex);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getNum());
        stmt.bindLong(5, entity.getTeamId());
 
        String teamName = entity.getTeamName();
        if (teamName != null) {
            stmt.bindString(6, teamName);
        }
 
        String cardNum = entity.getCardNum();
        if (cardNum != null) {
            stmt.bindString(7, cardNum);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(8, position);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Player readEntity(Cursor cursor, int offset) {
        Player entity = new Player( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sex
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getInt(offset + 3), // num
            cursor.getInt(offset + 4), // teamId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // teamName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cardNum
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // position
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Player entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSex(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNum(cursor.getInt(offset + 3));
        entity.setTeamId(cursor.getInt(offset + 4));
        entity.setTeamName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCardNum(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPosition(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Player entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Player entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Player entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
